---
title: Week 4 - Small Group Networks
sort: 4
format: 
  revealjs:
    css: /resources/custom_css.css
    theme: white
    progress: true
    transition: convex
    reveal_plugins: ['notes']
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = './')
#source("resources/preamble.R")
library(igraph)
library(tidygraph)
library(ggraph)
```


## Today's Dad Joke

My neighbor had the nerve to ring my doorbell at 3 o'clock in the morning.

<span class='fragment'>
Luckily I was still up playing the drums.
</span>

## Housekeeping

> - Practice asking a question on Discord

## Housekeeping

> - Self Assessment Reflections
> 	- Goals for the class
> 	- Feedback for me
> - I will also
> 	- Review the report on participation
> 	- Review your HW
> 	- Review your 3-2-1s

## Homework review

## What concepts are confusing?



## Review Questions

> - What is centralization?
> - When is a centralized network better?
> - What does "embedded" mean in the context of a network?
> - What is "transactive memory"?

## Review Questions

> - According to the Informal Networks article, why is it important to identify different kinds of networks?
> - What sorts of information can be learned from an advice network?
>	- A trust network?
> - Have you thought about the groups that you are in from a network perspective? What insights have you had?

## Technology break!

## Review Questions

> - What is network hierarchy? How does it differ from organizational hierarchy?
> - What is a core-periphery structure?
> - What is a structural hole?
> - What is multiplexity?

## Discussion Questions

> - How can there be too much information in a network?
> - In a world where many interactions are remote, often through platforms like Microsoft Teams, Slack, and X, does physical distance still matter, and if not, what is the number 1 indicator of a tie forming in social networks? 
> - How do organizations map informal networks without making people feel monitored or punished for being "too central" or "not connected enough"? What safeguards keep network analysis from turning into performance surveillance? 

## Discussion Questions

> - How can managers or researchers measure networks in real time to avoid relying only on static snapshots?
> - What are the downsides of relying on informal networks to make decisions?
> - Which direction does causality go?
> - Are all relationships formed due to selfishness? It seems like every relationship is transactional in one way or another. 
> - How useful are networks really? 

## Thursday

- R Review
- Work on R Lab 3 - Mutating and filtering
